name: CI-API
on:
  push:
    paths-ignore:
      - 'ui/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'ui/**'


jobs:
  check:
    name: Check-API
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Check-API"
      - name: Print
        run: exit 1


  another-check:
    name: Another check
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: exit 1

  merge-gatekeeper:
    name: Merge Gatekeeper
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1.2.1
        with:
          self: Merge Gatekeeper
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 45
          timeout: 15000
          ignored: "license/snyk (Percona Github Org), security/snyk (Percona Github Org), Another check"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}


