name: CI-API
on:
  push:
    paths-ignore:
      - 'ui/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'ui/**'


jobs:
  check:
    name: Check-API
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Check-API"


