name: CI-UI
on:
  push:
    paths:
      - 'ui/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ui/**'


jobs:
  check:
    name: Check-UI
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Check-UI"


